[project]
name = "mini-message-board"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.1",
    "flask-limiter>=3.12",
    "gunicorn>=23.0.0",
    "psycopg2>=2.9.10",
    "sqlalchemy>=2.0.43",
]
